name: Build and release

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: run build script
        run: |
          ./build.sh
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: built_package
          retention-days: 5
          path: |
            build

      - name: Zip the release
        uses: TheDoctor0/zip-release@0.4.1
        with:
          filename: 'release.zip'
          directory: build

      - name: Release on Github
        uses: softprops/action-gh-release@v0.1.5
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
              build/release.zip
